### ISSUE TITLE
End Date

### ISSUE THREAD

**Issue by laurenmackey** [laurenmackey/route-map#2]
End date for South should actually be June 18 - but maybe this is just because of weird D3 date stuff, in which case fine.

**Comment by laurenmackey** [comment]
So that is the price you have to pay (without a hacky solution) to show the San Blas islands on the South America map and have the islands shown on the Central America map after you transition.

I think it makes sense to show June 22nd as the last date because that is the last night in the San Blas islands and the islands are shown on the South America map.

**Comment by sapple-code** [comment]
The end date shown on the slider for the South America map is June 22nd. There is a slight bug in here because the date should be June 23rd. 

I think showing June 22nd/23rd is fine though because the South America map shows the San Blas islands being highlighted.
